[tool.poetry]
name = "cartm"
version = "0.1.0"
description = "Topic modelling with attention-based approach"
authors = ["Diyakov Ilya <s02210378@gse.cs.msu.ru>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
nltk = "^3.9.1"
scikit-learn = "^1.6.1"
numpy = "^2.2.2"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pandas = "^2.2.3"
seaborn = "^0.13.2"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"
flake8 = "^7.1.1"
pylint = "^3.3.4"

[tool.poetry.group.examples]
optional = true

[tool.poetry.group.examples.dependencies]
jupyter = "^1.1.1"
ipykernel = "^6.29.5"
ipywidgets = "^8.1.8"
seaborn = "^0.13.2"

[tool.poetry.group.cpu]
optional = true

[tool.poetry.group.cpu.dependencies]
jax = "^0.10.0"

[tool.poetry.group.gpu]
optional = true

[tool.poetry.group.gpu.dependencies]
jax = { extras = ["cuda13"], version = "^0.10.0" }

[tool.poetry.scripts]
download-nltk-data = "src.install:download_nltk_data"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
